version: 2
jobs:
  build:
    docker:
     - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - run: |
        git clone https://github.com/Hygieia/Hygieia.git
        cd Hygieia
        mvn clean install
        mvn docker:build
workflows:
  version: 2
  workflow:
    jobs:
    - build:
       filters:
            branches:
              only: master
