version: 2
jobs:
  build:
    docker:
     - image: circleci/openjdk:8-jdk
    steps:
    - checkout
    - run: |
        git clone https://github.com/Hygieia/Hygieia.git
        cd Hygieia
        ls
        mvn -v
        docker -v
workflows:
  version: 2
  workflow:
    jobs:
    - build:
       filters:
            branches:
              only: master
